### ISSUE TITLE
상품 구매 연결 끊김.

### ISSUE THREAD

**Issue by soooojinn** [taehunpb/SE_Project#58]
김태훈 씨 페이지 연결이 끊겼습니다.

사람 얼굴 두 개 있는 화면 꼭 구매 페이지랑 연결해주세요.

**Comment by mioky** [comment]
잘 좀 해주세요 김태훈씨

**Comment by taehunpb** [comment]
연결 했습니다... ㅠ 죄송합니다.ㅠㅠㅠㅠㅠ
